<?php

/**
 * About this page:
 * 
 * This is the server-side page that regisers log messages generated by the applet.
 * These messages should be sent with some frequency and regularity, so the
 * information payload will be pretty small. This page should never be viewed by
 * a user directly.
 */

error_reporting(E_ALL);
ini_set("display_errors", 1);

require_once("model/m_auto_posting.php");

// here is our data:
$problemId =  addslashes($_GET["problem_id"]);
$sessionId =  addslashes($_GET["session_id"]);
$javaClass =  addslashes($_GET["java_class"]);
$javaMethod = addslashes($_GET["java_method"]);
$message =    addslashes($_GET["message"]);
$timestamp =  addslashes($_GET["timestamp"]);

$success = post_logger($problemId, $sessionId, $javaClass, $javaMethod, $message, $timestamp);

// report back
if($success) {
  echo "post successful";
}else{
  echo "post failed!";
}

?>